import { ROLES, type Role } from './roles';

export const PERMISSIONS = {
  CREATE_PROJECT: 'CREATE_PROJECT',
  UPDATE_PROJECT: 'UPDATE_PROJECT',
  DELETE_PROJECT: 'DELETE_PROJECT',

  MANAGE_MEMBERS: 'MANAGE_MEMBERS',

  CREATE_TASK: 'CREATE_TASK',
  UPDATE_TASK: 'UPDATE_TASK',
  DELETE_TASK: 'DELETE_TASK',

  CREATE_COMMENT: 'CREATE_COMMENT',
  UPDATE_COMMENT: 'UPDATE_COMMENT',
  DELETE_COMMENT: 'DELETE_COMMENT',

  VIEW_REPORTS: 'VIEW_REPORTS',

  MANAGE_USERS: 'MANAGE_USERS',
} as const;

export type Permission =
  (typeof PERMISSIONS)[keyof typeof PERMISSIONS];

export const ROLE_PERMISSIONS: Record<
  Role,
  readonly Permission[]
> = {
  [ROLES.ADMIN]: [
    PERMISSIONS.CREATE_PROJECT,
    PERMISSIONS.UPDATE_PROJECT,
    PERMISSIONS.DELETE_PROJECT,

    PERMISSIONS.MANAGE_MEMBERS,

    PERMISSIONS.CREATE_TASK,
    PERMISSIONS.UPDATE_TASK,
    PERMISSIONS.DELETE_TASK,

    PERMISSIONS.CREATE_COMMENT,
    PERMISSIONS.UPDATE_COMMENT,
    PERMISSIONS.DELETE_COMMENT,

    PERMISSIONS.VIEW_REPORTS,

    PERMISSIONS.MANAGE_USERS,
  ],

  [ROLES.MANAGER]: [
    PERMISSIONS.CREATE_PROJECT,
    PERMISSIONS.UPDATE_PROJECT,

    PERMISSIONS.MANAGE_MEMBERS,

    PERMISSIONS.CREATE_TASK,
    PERMISSIONS.UPDATE_TASK,
    PERMISSIONS.DELETE_TASK,

    PERMISSIONS.CREATE_COMMENT,
    PERMISSIONS.UPDATE_COMMENT,
    PERMISSIONS.DELETE_COMMENT,

    PERMISSIONS.VIEW_REPORTS,
  ],

  [ROLES.STAFF]: [
    PERMISSIONS.CREATE_TASK,
    PERMISSIONS.UPDATE_TASK,

    PERMISSIONS.CREATE_COMMENT,
    PERMISSIONS.UPDATE_COMMENT,
  ],
};